baseurl = "http://localhost/basyx/"
#baseurl = "http://localhost/"
#baseurl = ""
title = "Eclipse BaSyx"
theme = "hugo-universal-theme"
#themesDir = "../.."
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
# disqusShortname = "devcows"
# Enable Google Analytics by entering your tracking code
# googleAnalytics = "UA-XXXXX-X"
googleAnalytics = ""
pluralizelisttitles = "false"

# Define the number of posts per page
paginate = 10
# Adding this COMMENT for testing

[menu]

# Main menu

#[[menu.main]]
#    name = "Home"
#    url  = "/"
#    weight = 10
	
#[[menu.main]]
#	name = "Blog"
#	url  = "/blog/"
# 	weight = 15

[[menu.main]]
    name = "About"
    url  = "/about/"
    weight = 20
	
[[menu.main]]
    name = "Benefits"
    url  = "/benefits/"
    weight = 25

[[menu.main]]
    name = "Concepts"
    url  = "/concepts/"
    weight = 1
    parent = "developer" 

[[menu.main]]
    name = "Architecture"
    url  = "/architecture/"
    weight = 2
    parent = "developer"

[[menu.main]]
    identifier = "ecosystem"
    #name = "Partners & References"
    name = "Ecosystem"
    url  = "/ecosystem/"	
    weight = 30

[[menu.main]]
    identifier = "overview"
	name = "Overview"
	url  = "/overview/"
 	weight = 1
    parent = "ecosystem"

[[menu.main]]
    identifier = "partners"
	name = "Partners"
	url  = "/partners/"
 	weight = 2
    parent = "ecosystem"

[[menu.main]]
    identifier = "success-stories"
	name = "Success Stories"
	url  = "/success-stories/"
 	weight = 3
    parent = "ecosystem"

[[menu.main]]
    identifier = "getting-started"
    name = "Getting Started"
    url  = "/getting-started/"	
    weight = 45

[[menu.main]]
    identifier = "videos"
    name = "    Videos    "
    url  = "/videos/"
    weight = 1
    parent = "getting-started"

[[menu.main]]
    name = "    Open Hour   "
    url  = "https://www.iese.fraunhofer.de/en/customers_industries/digitalisierung-produktion/industrie40/basyx_open_hour.html"
    weight = 2
    parent = "getting-started"

[[menu.main]]
    identifier = "developer"
    name = "Developer"
    url  = "/developer/"
    weight = 55
    
#[[menu.main]]
#	name = "Details"
#	url  = "/"
#	weight = 20
	
#[[menu.main]]
#    name = "Use Cases"
#    url  = "/use case/"
#     url  = "/"
#    weight = 25
	
#[[menu.main]]
#    name = "Forum"
#    url  = "https://www.eclipse.org/forums/index.php/f/386/"
#    weight = 30

#[[menu.main]]
#    name = "Documentation"
#    url  = "https://wiki.eclipse.org/BaSyx"	
#    weight = 35

#[[menu.main]]
#	name = "Offers"
#	url  = "/offer/"
# 	weight = 35

#[[menu.main]]
#    identifier = "download"
#    name = "Download"
#    url  = "https://github.com/eclipse-basyx"	
#    url  = "/download/"	
#    weight = 45
#    parent = "contributing"
	
[[menu.main]]
    identifier = "contributing"
    name = "Contributing"
    url  = "https://wiki.eclipse.org/BaSyx_/_Developer_/_Contributing"
    weight = 3
    parent = "developer"

[[menu.main]]
    name = "Wiki"
	url  = "https://wiki.eclipse.org/BaSyx"
    weight = 4 
    target = "_blank"
    parent = "developer"

#[[menu.main]]
#    name = "Mailist"
#    url  = "/calendar/"
#    weight = 50


# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "Git Repository"
    url = "https://github.com/eclipse-basyx"
    pre = "<i class='fa fa-2x fa-git-square'></i>"

#[[menu.topbar]]
#    weight = 2
#    name = "Facebook"
#    url = "http://facebook.com"
#    pre = "<i class='fa fa-2x fa-facebook'></i>"

#[[menu.topbar]]
#   weight = 3
#   name = "Twitter"
#   url = "http://twitter.com/Appstacle"
#   pre = "<i class='fa fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 4
    name = "Email"
    url = "mailto:basyx-dev@eclipse.org"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Admin"
    defaultKeywords = ["industrie 4.0","industry 4.0", "iot", "basys 4.0", "basys 4.2", "basyx", "smart production", "digitalization", "cyber physical systems", "BaSyx offers", "Digital Twin", "Asset Administration Shell"]
    defaultDescription = "Eclipse BaSyx Community Website"
    custom_css = ["css/custom.css"]

    # Google Maps API key (if not set will default to not passing a key.)
    #googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = ""

    #copyright = "Copyright © 2021 The Eclipse Foundation. All Rights Reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    logo = "img/basyxlogo.png"
    logo_small = "img/basyxlogo.png"
   #address = """<p><strong>Universal Ltd.</strong>
   #     <br>13/25 New Avenue
   #     <br>Newtown upon River
   #     <br>45Y 73J
   #     <br>England
   #     <br>
   #     <strong>Great Britain</strong>
   #   </p>
   #   """
   # latitude = "-12.043333"
   # longitude = "-77.028333"

[Permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs">Contact us on <a href="mailto:basyx-dev@eclipse.org">basyx-dev@eclipse.org</a></p>
      <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      </p>
      """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
    title = "Features"
    
[params.video]
    enable = false
    title = "Basissystem Industrie 4.0"
    subtitle = "Eine offene Plattform für die vierte industrielle Revolution"
    url  = "http://www.basys40.de/wp-content/uploads/2014/09/BaSys-HP.mp4"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Partners"
    subtitle = ""

[params.recent_posts]
    enable = false
    title = "Our latest news"
    subtitle = ""

[params.about]
    enable = true
    title = "Eclipse BaSyx Project"
	
[params.testimonials]
    enable = true
    title = "Testimonials"
    subtitle = "Have a look what BaSyx users & partners said about the open source Industrie 4.0 platform."

#[params.ecosystem]
#    enable = true
#    title = "BaSyx Ecosystem"
#    categories = true
#    search = true
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true